### PR TITLE
Add OpenSUSE support

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Create a new file install_opensuse.sh that works on OpenSUSE systems, such as Tumbleweed.

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
Should probably squash and merge if you accept.

**Comment by dylanmtaylor** [comment]
Latest commit adds support to the install_generic.sh as well.

**Comment by dylanmtaylor** [comment]
I'm going to work on a cleaner solution, maybe simplify the whole installer. I've got the method down in my makefile project, but need to make it more generic.

**Comment by qrpike** [comment]
@dylanmtaylor 

Sounds good, just make sure there are no external dependencies to install on a vanilla machine.

Thanks for your help!

**Pull request closed without merging**
