### PR TITLE
Crash info for Photoshop CC users

### PR DESCRIPTION
**Pull request by Jaspur**

### CODE REVIEW

**Comment by aungthurhahein** [comment]
I think it's because of fonts overloading.

**Comment by qrpike** [comment]
Have you restarted your computer and then run FontBook to try to load in and cache all fonts before running PS?

**Comment by Jaspur** [comment]
Yes. PS is the only program not working anymore.

**Comment by qrpike** [comment]
What are the specs on your machine? I've never heard of anyone having this issue. Another option would be to open FontBook and delete the fonts you don't want.

**Comment by Jaspur** [comment]
MacBook Pro (Retina, 15-inch, Late 2013), 2,3 GHz Intel Core i7, 16 GB 1600 MHz DDR3, NVIDIA GeForce GT 750M 2048 MB - that should be more then enough for PS and the fonts

**Comment by hoxxep** [comment]
I've got the same issue (with the top-end early 2014 15" MacBook Pro) when I try to open the dropdown from the text panel (changing font in the main toolbar is still fine however). I think it's because of the sheer number of fonts more than anything, and PS might have a max size on the array it stores the fonts/previews in or something? I'll restart and try again...

**Edit:** Seemed fine after restarting then just as I went to update this comment it crashed... Hmm.

It would be nice if the fonts were installed as user fonts in FontBook, would make removing them a little easier so that PS doesn't crash.

**Edit 2:** Validating fonts by selecting all fonts in FontBook (Cmd+A) and doing File>Validate Fonts. It's bringing up all fonts with errors/warnings. I'll compile a list and remove all fonts with errors and warnings, delete my PS cache and report back if this fixes the issue.

See more: https://helpx.adobe.com/photoshop/kb/troubleshoot-fonts-photoshop-cs5.html

**Edit 3:** Having removed all fonts with errors/warnings, cleared caches and even ran the entire Font Test script from Adobe too, the only working solution for me has been turning off font previews. Well, it hasn't crashed yet at least...

Either it's the sheer number or there's one or two fonts which pass all the tests but crash the previewer - sadly there's no quick way to check this.

**Comment by qrpike** [comment]
https://helpx.adobe.com/photoshop/kb/troubleshoot-fonts-photoshop-cs5.html

Seems disabling font preview fixes the issue for users.

**Comment by Jaspur** [comment]
Should I change it because of the merge-conflict, so it can be merged, or? 😌

**Comment by hoxxep** [comment]
Perhaps a warning to turn off font preview in Photoshop CC (and CS6 in my case) would be wiser :wink:

Not sure what we should do about fixing/not installing the broken fonts in the first place though - not that it makes any difference to Photoshop? I have three screengrabs of the list of broken fonts if desired.

**Comment by qrpike** [comment]
We could make a list and when installing have the script skip over the broken ones you have a list for. When you remove them (the broken ones) does Font Preview work in PS ?

**Comment by hoxxep** [comment]
Sadly font preview still doesn't work, since I reckon that might be due to sheer number rather than a specific font. For reliability with other software I can compile a textual list of the broken fonts from the screen grabs I got though?

**Comment by qrpike** [comment]
I dont think removing the fonts from the install script will do any good. I (also) think it's just the sheer number of fonts ( ~1660 ).

We could however find the 250 most popular fonts ( according to sortby on google fonts page ). And give the option when installing to either install the most popular ones, or the entire list of fonts.

**Comment by hoxxep** [comment]
The 250 most popular option sounds like a solid idea and good solution. Would we have to scrape the site manually and compile a list of the top 250 fonts?

Also, is there a quick way to remove the installed fonts?

**Comment by qrpike** [comment]
250 Topic: Manually is probably the only way. Maybe top 100? lol

Uninstall: There isn't a quick way to do it. Only thing I can think of is to generate a list of fonts from the downloaded fonts folder and then make a new script to try to remove all files in that list.

**Comment by hoxxep** [comment]
Hmm, it's possible to use either iMacros or Python/selenium to scrape it? Probably quicker to script it than do it by hand ;)

That's not too big of a deal, cheers!

**Comment by aungthurhahein** [comment]
About uninstalling fonts, make a list of fonts while installing and create a uninstall script is the easiest way like qrpike suggested. 

  install.sh

```
rm -R -- */
rm *.txt
rm *.json
ls > .google_font_list
cd ..
sudo mv fonts/* /usr/local/share/fonts/
```

uninstall.sh

```
#!/bin/bash
path='/usr/local/share/fonts'
font_list='/usr/local/share/fonts/.google_font_list'
while read font
do
   rm -rf $path/$font
done < $font_list
echo "All Google fonts uninstalled."
```

**Comment by qrpike** [comment]
I went ahead and created a uninstall script. Seemed to work for me, if someone could test it and let me know that would be great.

`curl https://raw.githubusercontent.com/qrpike/Web-Font-Load/master/uninstall.sh | sh`

Thanks,

**Comment by aungthurhahein** [comment]
I just got an idea. Instead of several install and uninstall scripts, the os can be detected with the following condition.
Please confirm the `uname` output for Arch Linux and MAC. (http://www.wikiwand.com/en/Uname)

```
osdetect=$(uname)
filepath="unknown"
if [[ "$osdetect" == 'Linux' ]]; then
   filepath='/usr/local/share/fonts/'
elif [[ "$osdetect" == 'Darwin' ]]; then
  filepath='/Library/Fonts/'
elif [[ "$osdetect" == 'Arch Linux' ]]; then
    filepath='/usr/share/fonts/'
fi
```

**Comment by qrpike** [comment]
On Mac OSX 10.10 I get `Darwin`

**Comment by davelab6** [comment]
>  Would we have to scrape the site manually and compile a list of the top 250 fonts?

No, you can use https://developers.google.com/fonts/docs/developer_api like `https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity`

**Pull request closed without merging**
